name: 'Sign in to Shisho Cloud'
description: 'signs in to Shisho Cloud'
inputs:
  bot-id:
    description: 'ID of the bot to sign in as'
    required: true
  expires-in-minutes:
    description: 'Expiration time of the access token in minutes'
    required: false
    default: ''
runs:
  using: 'node16'
  main: 'dist/index.js'
